[versions]

kotlin = "1.7.10"
androidx-core = "1.9.0"
camerax = "1.1.0"
compose = "1.2.1"
compose-compiler = "1.3.1"
appcompat = "1.4.0"
material = "1.6.1"
material3 = "1.0.0-alpha14"
lifecycle = "2.5.1"
navigation = "2.5.2"

[libraries]

androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }

lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

compose-activity = { module = "androidx.activity:activity-compose", version.ref = "appcompat" }

compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }

material = { module = "com.google.android.material:material", version.ref = "material" }

camerax-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
camerax-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camerax-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camerax-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }

[bundles]

compose = [
    "compose-runtime",
    "compose-ui",
    "compose-tooling-preview",
    "compose-ui-tooling",
    "compose-foundation"
]

internal-camerax = [
    "camerax-camera2",
    "camerax-lifecycle",
    "camerax-view"
]
